### ISSUE TITLE
为啥这个项目这么多star

### ISSUE THREAD

**Issue by zgimszhd61** [zijie0/HumanSystemOptimization#17]
怎么推广的？买的量吗？
你们是怎么知道这个仓库的呀

**Comment by joostshao** [comment]
你和我想的一样

**Comment by zijie0** [comment]
我也想知道……我在v2ex发过一次，其它就没了。

**Comment by mulplue** [comment]
我在github trending上看到了这个project，很多程序员应该每天都会看一遍trending，也许这是star的一个来源。以及home里可以看到following user的star动态，大家每个人看到都去star的话就会指数级增长
另外，作为一个工作强度较大的程序员，我对有科学知识支撑的养生习惯很有兴趣，并希望长期维持，我想在我们的国情下，或许有很多人有类似的想法lol

**Comment by zgimszhd61** [comment]
我也是只看到了trending，但是trending上榜之前的情况我一无所知.
