### ISSUE TITLE
进食和禁食的歧义

### ISSUE THREAD

**Issue by wulnm** [zijie0/HumanSystemOptimization#8]
在[fasting-的实践](https://github.com/zijie0/HumanSystemOptimization#fasting-%E7%9A%84%E5%AE%9E%E8%B7%B5)部分，**进食**和**禁食**这两个词存在一定的歧义，容易让人以为是用拼音打错字。（我不确定是不是真的打错字了）

内容如下：
> 由于长时间的禁食难度较大，所以绝大多数的研究都专注于间歇性  **禁食**  ，也就是 time restricted feeding。简单来说就是跟前面的小白鼠实验一样，在一天的固定时间段来吃东西（跟睡眠周期对齐），而其它时间段都不摄入任何食物的做法。这里简单整理为基础和高阶两个版本：
...
高阶：目前研究结果中最理想的  **进食**  窗口是 8 小时，结合社会习俗等，一般比较合理的时间在 10-18 点或 12-20 点的范围。看起来不吃早饭并不是什么坏事 :)
...

**Comment by zijie0** [comment]
感谢提出，前面的确是打错了，间歇性禁食对应的应该是 intermittent fasting，而不是 time restricted feeding。
后面的进食窗口没有打错哈。
